#!/bin/sh

# /etc/rc.local
# This script will be executed on boot after all other scripts


# Log what is happening in startup for debug
exec 2> /tmp/data-act.log
exec 1>&2
set -x

#Start the initial playbook to pull the repo
ansible-playbook -i  "localhost," -c local /startup/start.yml

#export the path of host file
export ANSIBLE_HOSTS=/startup/hosts

#This section selects which playbook to use and whether to run as dev or prod

SERVER_TYPE="WEB_API"
ENV="ENV=dev BRANCH=development"

if [ "$SERVER_TYPE" == "WEB_API" ]; then

      ansible-playbook -i /startup/hosts -c local /data-act/install/data-broker-web-api/site.yml --extra-vars "$ENV"

elif [ "$SERVER_TYPE" == "WEB" ]; then

      ansible-playbook -i /startup/hosts -c local /data-act/install/data-broker-web-app/site.yml

elif [ "$SERVER_TYPE" == "MANAGER" ]; then

        echo "TODO"

elif [ "$SERVER_TYPE" == "VALIDATOR" ]; then

      ansible-playbook -i /startup/hosts -c local /data-act/install/data-broker-validation/site.yml --extra-vars "$ENV"

elif [ "$SERVER_TYPE" == "API" ]; then

        echo "TODO"
else

  echo "SERVER SETUP FAILED"

fi
